name: pklawit demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 
  
  
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print the event that triggered the workflow
        run: echo  The event that triggered ${{ github.event.name }}
