name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
  pull:
    branches:
      - main
      
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '30 5,17 * * *'
  
  workflow_dispatch:
    
  
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print the event that triggered the workflow
        run: echo  The event that triggered ${{ github.event.name }}
